services:
  - type: web
    name: expense-tracker-bot
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn main.wsgi:application --timeout 60 --workers 2"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
